[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install"

[deploy]
startCommand = "cd backend && node src/config/migrate.js && node src/server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "web"